### ISSUE TITLE
Cancel edit does not work

### ISSUE THREAD

**Issue by hkeward** [taniarascia/vue-tutorial#1]
Pressing the `Cancel` button to get out of edit mode results in the row being updated to the input values, rather than reset to the initial values for that row.
e.g. `Edit` -> update a field -> `Cancel`, the values you changed remain changed & are saved

I fixed this using the following:

EmployeeTable.vue
```
    ...

    <td v-if="editing === employee.id">
        ...
        <button class="muted-button" @click="cancelEdit(employee)">Cancel</button>
    </td>
    <td v-else>
        <button @click="editMode(employee)">Edit</button>
        ...
    </td>

    ...

    editMode(employee) {
        this.cachedEmployee = Object.assign({}, employee);
        this.editing = employee.id;
    },
    cancelEdit(employee) {
        Object.assign(employee, this.cachedEmployee);
        this.editing = null;
    },

    ...
```

**Comment by KeivanDjafarizad** [comment]
That's great, thanks, I've encountered this bug too. 
Would you mind share why your solution works in the Vue context, for educational purpose?

Great tutorial nonetheless, keep up the good work

**Comment by hkeward** [comment]
@KeivanDjafarizad 
The reason why the Cancel doesn't work as it is laid out in the tutorial is that `v-model` binds the input fields to the employee attributes, so when you change them you are actually changing the data in employee itself as you edit, whether or not you hit save. If you don't hit `Save` these changes are not pushed to the API, however they will still show up locally until you refresh the page.

I have made it so that when editMode is entered, the state of the object at the time when the edit button is pressed is saved into another object - `this.cachedEmployee`. You are still changing the state of the employee as you  edit, however if you hit cancel, we revert those changes by setting the altered employee to the cached version of the employee.

I hope this makes sense; I am still very new at this myself!

**Comment by KeivanDjafarizad** [comment]
Amazing, I got through the first part of your explanation by myself, the thing that was strange to me was about how you save a local object. I tried to save the initial employee object inside a data key but this made it a reacting object (I think) and it bound the value to the object even though it was saved one time when you hit `edit`. 
So if you go with `this.cachedEmployee = Object.assign({}, employee)` you're creating a non-reactive object, am I right?
And when you invoke `cancelEdit(employee)`, the object `employee` is reactive, so you can directly assign to it the value of `this.cachedEmployee` and this will modify the reactive object, right? I'm trying to wrap my head around how objects are treated in the Vue flow.

**Comment by hkeward** [comment]
This understanding sounds about right to me!

 What we're doing when we invoke `this.cachedEmployee = Object.assign({}, employee)` is making a *copy* of the initial employee object, whose values are equal to whatever the values of `employee` were when we call the `Object.assign()`. This means that we now have 2 separate objects; `employee`, which is reactive because of the `v-model`, and `this.cachedEmployee`, which is a separate object and is not reactive.

If we instead did something like set `this.cachedEmployee = employee`, we are not actually creating a new object, we are setting `this.cachedEmployee` to point at the same object that `employee` points to (objects are pass-by-reference in JS!). This means that changes to `employee` will change the same object that `this.cachedEmployee` is pointing to. Likewise, if you made changes to `this.cachedEmployee`, `employee` would also change - they are just two different variables that refer to the same object. This is not the behaviour we want, so we instead make a copy of the employee object so that changes to `employee` do not affect it. Since `employee` is reactive and `this.cachedEmployee` points to the same object, changes to `this.cachedEmployee` in this scenario would be reactive.

> And when you invoke cancelEdit(employee), the object employee is reactive, so you can directly assign to it the value of this.cachedEmployee and this will modify the reactive object, right?

Yes, this is right!

**Comment by KeivanDjafarizad** [comment]
That's great, thanks! Cheers!

**Comment by taniarascia** [comment]
Sorry, I noticed this error a while ago and haven't gotten to updating the example. If you were able to submit a PR for your fix, I would highly appreciate it! Otherwise, I'll work on getting it updated soon.
