### ISSUE TITLE
UI issue - buttons

### ISSUE THREAD

**Issue by InaFK** [taniarascia/vue-tutorial#3]
Hi!
I want to help to fix some small issue:
https://prnt.sc/o01yvl

I suggest the colution:
https://prnt.sc/o00qrg
+
https://prnt.sc/o01xy8

(And if to be perfectionist: http://prntscr.com/o024nt)

Thank you for your work, Tania!

**Comment by taniarascia** [comment]
Feel free to make a PR updating the style.
