### ISSUE TITLE
When one row is in editing, the other rows still can be edited 

### ISSUE THREAD

**Issue by Charles-Hsu** [taniarascia/vue-tutorial#9]
EmployeeTable.vue, added 
 
`<button @click="editMode(employee)" :disabled="editing != null">Edit</button>`
`<button @click="$emit('delete:employee', employee.id)" :disabled="editing != null">Delete</button>`

and in the style part:

` button:disabled {`
` opacity:0.4;`
`}`

**Comment by taniarascia** [comment]
I'm sorry, I don't understand this issue.

**Comment by Charles-Hsu** [comment]
When we edit items of an employee, I think we should disable the buttons of action (Edit and Delete) for the other employees.

[Vue2 Custom directive to disable button conditionally](https://stackoverflow.com/a/52988381/3309645)

So I modified EmployeeTable.vue by the following code  
 
`<button @click="editMode(employee)" :disabled="editing != null">Edit</button>`
`<button @click="$emit('delete:employee', employee.id)" :disabled="editing != null">Delete</button>`

and added

` button:disabled {`
` opacity:0.4;`
`}`

in the style part. And come out the result as following

https://imgur.com/ej70fcJ

**Comment by taniarascia** [comment]
Ah, got it, thanks for clarifying @Charles-Hsu. If you'd like to make a PR to this demo as well as the tutorial itself, we can add this in! If not, I'll close the issue.

**Comment by Charles-Hsu** [comment]
If you can update the code by yourself, I will feel very appreciated, because I do not know how to make a PR. :)
